#!/usr/bin/env bash
# Refuse a second place that knows the production address.
#
# The generated hostname lives in exactly one runtime location, written only by
# scripts/sync-base-host.sh from Terraform's public_ip output. Everywhere else
# an address appears it is documentation or an example, and this guard is what
# stops the next one from quietly becoming a fourth source of truth — which is
# how the platform arrived at three of them without anybody deciding to.
#
# The check is an allowlist rather than a pattern, because "looks like an
# example" is not something a regex can be trusted to decide about a string that
# is also a live production endpoint.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

fail() { echo "FAIL: $*" >&2; exit 1; }

# The single generated runtime value.
GENERATED_FILE="deploy/platform-chart/values.yaml"

# Files permitted to contain an address-derived hostname, and why. Each is prose
# or a usage example a human reads, never a value a machine consumes at runtime.
ALLOWED=(
  "$GENERATED_FILE"                       # the generated value itself
  "README.md"                             # states the current live endpoint
  "docs/onboarding.md"                    # example configuration
  "docs/runbook.md"                       # example commands
  "docs/cost.md"                          # prose
  "scripts/register-webhook.sh"           # usage line: "e.g. ..."
  "scripts/base-host.test.js"             # asserts the conversion, by definition
  "scripts/base-host.js"                  # 1.2.3.4 illustrations; a test in
                                          # base-host.test.js asserts this file
                                          # never contains the production address
  ".github/workflows/preview-build.yml"   # input description: "e.g. ..."
)

# What counts as a cluster endpoint: an IPv4-derived nip.io hostname that is
# not loopback and not a placeholder. 127-0-0-1.nip.io appears throughout the
# kind suite and in the chart guards, where it is the point rather than a
# hardcoded production address, and example.nip.io is what the renderer is fed
# in CI.
#
# Plain read loop rather than mapfile: this has to run on the bash that ships
# with macOS, which is 3.2 and has neither mapfile nor readarray.
hits=()
while IFS= read -r line; do
  [[ -n "$line" ]] && hits+=("$line")
done < <(
  grep -rIoE '([0-9]{1,3}[-.]){3}[0-9]{1,3}\.nip\.io' \
    --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=.terraform \
    --exclude='*.tfstate' --exclude='*.tfstate.backup' . 2>/dev/null \
    | grep -vE '127[-.]0[-.]0[-.]1\.nip\.io' \
    | cut -d: -f1 | sed 's|^\./||' | sort -u
)

unexpected=()
for hit in "${hits[@]}"; do
  allowed=false
  for a in "${ALLOWED[@]}"; do [[ "$hit" == "$a" ]] && allowed=true && break; done
  $allowed || unexpected+=("$hit")
done

if (( ${#unexpected[@]} )); then
  fail "these files name a cluster endpoint and are not on the allowlist:
$(printf '      %s\n' "${unexpected[@]}")
      A hostname derived from the node's address must come from
      $GENERATED_FILE, which scripts/sync-base-host.sh writes from Terraform's
      public_ip output. If one of these is documentation, add it to ALLOWED in
      $(basename "$0") with a reason. If it is consumed at runtime, it is a
      second source of truth and the VM being replaced will silently break it."
fi

# The generated value must still be a hostname this repository could have
# generated, rather than something typed in by hand.
current="$(awk '/^baseHost:/ { print $2; exit }' "$GENERATED_FILE" || true)"
[[ -n "$current" ]] || fail "$GENERATED_FILE has no baseHost"

octets="${current%.nip.io}"
[[ "$octets" != "$current" ]] || fail "baseHost '$current' is not a nip.io hostname; if this cluster moved to a real domain, this guard needs updating deliberately"

dotted="${octets//-/.}"
regenerated="$(node scripts/base-host.js "$dotted")" \
  || fail "baseHost '$current' does not round-trip through scripts/base-host.js — it was not generated by it"
[[ "$regenerated" == "$current" ]] || fail "baseHost '$current' is not what base-host.js produces for $dotted (got $regenerated)"

echo "  ok: one generated endpoint ($current), $(( ${#hits[@]} - 1 )) documentation references"
echo "base host configuration is consistent"
